# Generated by Django 3.2.9 on 2022-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
